// Cache version — updated automatically by build.sh on every deploy.
// Format: zsozso-v0.YYYYMMDD.HHmm-COMMITHASH (date+time+git hash)
const CACHE_NAME = 'zsozso-v0.20260309.1646-4390b62b';

// ── SW-side log ring buffer (max 100) ──
const _swLogBuffer = [];
const _SW_LOG_MAX = 100;

function _ts() {
    const d = new Date();
    return d.toLocaleTimeString('en-GB', { hour12: false }) + '.' +
        String(d.getMilliseconds()).padStart(3, '0');
}

const LOG = (...args) => {
    const text = args.map(a => typeof a === 'string' ? a : JSON.stringify(a)).join(' ');
    const entry = _ts() + ' ' + CACHE_NAME + ' [SW] ' + text;
    _swLogBuffer.push(entry);
    if (_swLogBuffer.length > _SW_LOG_MAX) _swLogBuffer.shift();
    console.log(`[SW ${CACHE_NAME}]`, ...args);
    _forward(entry);
};
const ERR = (...args) => {
    const text = args.map(a => typeof a === 'string' ? a : JSON.stringify(a)).join(' ');
    const entry = _ts() + ' ' + CACHE_NAME + ' [SW ERR] ' + text;
    _swLogBuffer.push(entry);
    if (_swLogBuffer.length > _SW_LOG_MAX) _swLogBuffer.shift();
    console.error(`[SW ${CACHE_NAME}]`, ...args);
    _forward(entry);
};

// Forward log lines to the main page so the in-app Log tab can display them
function _forward(text) {
    self.clients.matchAll({ type: 'window' }).then(clients => {
        clients.forEach(c => c.postMessage({ type: '__ZSOZSO_SW_LOG', text: text }));
    });
}

LOG('Script evaluated');

// We don't use a pre-cache list because Dioxus generates hashed filenames
// (e.g. zsozso-dxhABC123.js) that change with every build.
// Instead we cache at runtime: files are cached on first load.

self.addEventListener('message', event => {
    if (event.data && event.data.type === 'GET_LOGS') {
        event.ports[0].postMessage({ logs: _swLogBuffer.slice() });
        return;
    }
    if (event.data && event.data.type === 'CLEAR_LOGS') {
        _swLogBuffer.length = 0;
        return;
    }
    LOG('Message received:', event.data);
    if (event.data && event.data.type === 'GET_VERSION') {
        event.ports[0].postMessage({ version: CACHE_NAME });
        LOG('Replied with version:', CACHE_NAME);
    }
});

self.addEventListener('install', event => {
    LOG('Install event — calling skipWaiting()');
    // Activate immediately, don't wait for the old SW to stop
    self.skipWaiting();
});

self.addEventListener('activate', event => {
    LOG('Activate event — cleaning old caches');
    // 1. Claim clients IMMEDIATELY
    event.waitUntil(self.clients.claim());

    // 2. Then proceed with cleanup and notifications
    // Delete old cache versions
    event.waitUntil(
        caches.keys().then(keys => {
            const old = keys.filter(k => k !== CACHE_NAME);
            LOG('Existing caches:', keys, '| Deleting:', old);
            // Track whether this is a genuine update (old caches exist)
            const isUpdate = old.length > 0;
            return Promise.all(old.map(k => caches.delete(k))).then(() => isUpdate);
        }).then(isUpdate => {
            LOG('Old caches deleted, calling clients.claim()');
            return self.clients.claim().then(() => isUpdate);
        }).then(isUpdate => {
            // Only notify clients to reload when we actually replaced an older version.
            // On iOS the SW can be terminated and re-activated by the OS —
            // that is NOT an update and must not trigger a reload loop.
            if (isUpdate) {
                return self.clients.matchAll({ type: 'window' }).then(clients => {
                    clients.forEach(c => c.postMessage({ type: '__ZSOZSO_SW_UPDATED', version: CACHE_NAME }));
                    LOG('Update detected — notified', clients.length, 'client(s)');
                });
            } else {
                LOG('No old caches found — not an update, skipping reload notification');
            }
        })
    );
});

// ── Asset loader (generated by bundle_sw.js -z) ─────────────────────────────

var __ASSETS = null;

async function _loadAssets() {
    if (__ASSETS) return;
    LOG('Loading compressed assets from assets.json.gz …');
    var resp = await fetch('/app/assets.json.gz');
    if (!resp.ok) throw new Error('Failed to load assets: ' + resp.status);
    var ds = new DecompressionStream('gzip');
    var decompressed = resp.body.pipeThrough(ds);
    var text = await new Response(decompressed).text();
    __ASSETS = JSON.parse(text);
    LOG('Assets loaded:', Object.keys(__ASSETS.assets).length, 'files');
}

// Eagerly load assets during install (before activation)
self.addEventListener('install', function(event) {
    event.waitUntil(_loadAssets());
});

function _serveEmbedded(key) {
    if (!__ASSETS) return null;
    var data = __ASSETS.assets[key];
    if (!data) return null;
    var mime = __ASSETS.mime[key] || 'application/octet-stream';
    return new Response(_b64ToArrayBuffer(data), {
        status: 200,
        headers: { 'Content-Type': mime }
    });
}

function _b64ToArrayBuffer(b64) {
    var bin = atob(b64);
    var len = bin.length;
    var bytes = new Uint8Array(len);
    for (var i = 0; i < len; i++) bytes[i] = bin.charCodeAt(i);
    return bytes.buffer;
}

function _serve404(pathname) {
    var html = '<!DOCTYPE html><html><head><meta charset="UTF-8">'
        + '<meta name="viewport" content="width=device-width,initial-scale=1.0">'
        + '<title>404 — Not Found</title>'
        + '<style>body{display:flex;align-items:center;justify-content:center;height:100vh;margin:0;'
        + 'font-family:sans-serif;background:#f5f5f5;color:#333;text-align:center}'
        + 'h1{font-size:4em;margin:0;color:#dc3545}p{color:#666;margin:8px 0}'
        + 'a{color:#17a2b8;text-decoration:none;font-weight:bold}'
        + '</style></head><body><div>'
        + '<h1>404</h1>'
        + '<p>The requested resource was not found.</p>'
        + '<p style="font-size:0.85em;font-family:monospace;word-break:break-all">' + pathname + '</p>'
        + '<p style="margin-top:24px"><a href="./">← Back to app</a></p>'
        + '</div></body></html>';
    return new Response(html, {
        status: 404,
        headers: { 'Content-Type': 'text/html; charset=utf-8' }
    });
}

// Baked-in base path prefix for stripping (set by bundle_sw.js).
var __BASE_PREFIX = '/app/';

self.addEventListener('fetch', function(event) {
    var url = new URL(event.request.url);

    // Let the asset bundle pass through to network (needed for lazy reload)
    if (url.origin === self.location.origin && url.pathname.endsWith('assets.json.gz')) return;

    // Navigation requests → serve embedded index.html
    if (event.request.mode === 'navigate') {
        event.respondWith(_loadAssets().then(function() { return _serveEmbedded('index.html') || _serve404(url.pathname); }));
        return;
    }

    // Cross-origin — fall through to normal network fetch
    if (url.origin !== self.location.origin) return;

    // Strip the base prefix to get the embedded-asset key.
    // Example: base="/app/", pathname="/app/assets/foo.js" → "assets/foo.js"
    var relative = url.pathname;
    if (__BASE_PREFIX !== '/' && relative.startsWith(__BASE_PREFIX)) {
        relative = relative.substring(__BASE_PREFIX.length);
    } else if (relative.startsWith('/')) {
        relative = relative.substring(1);
    }

    event.respondWith(
        _loadAssets().then(function() {
            return _serveEmbedded(relative) || _serve404(url.pathname);
        })
    );
});
